#!/usr/bin/env bash
# Usage: tmpme
# Summary: Move to a temporary directory
# Help: Create a temporary directory and drop me in it.
# Copy any files supplied as arguments. Creates a new 
# shell, must exit using: "exit-tmpme"
tmpme=`mktemp -d`
[ $1 ] && cp -r $* $tmpme
cd $tmpme
init="alias exit='echo \"exit disabled, type exit-tmpme instead\"' ; alias exit-tmpme='\exit' ; . ~/.bashrc"
bash --init-file <(echo $init)
rm -rf $tmpme
